name: capstonefinal1
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  auto_layout: ^1.0.4

  auto_animated: ^3.0.0
  koukicons: ^2.0.3
  animated_dialog_box: ^0.0.2
  animated_stack: ^0.2.0
  animated_text_kit: ^2.0.0
  path_provider: ^2.0.2

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - images/

    - assets/ml.txt





  fonts:
    - family: Gloria Hallelujah
      fonts:
        - asset: fonts/GloriaHallelujah-Regular.ttf

    - family: PT Serif
      fonts:
        - asset: fonts/PTSerif-Regular.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Mukta
      fonts:
        - asset: fonts/Mukta-Regular.ttf

    - family: Architects Daughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf

    - family: Girassol
      fonts:
        - asset: fonts/Girassol-Regular.ttf

    - family: Permanent Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: Shadows Into Light
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf


    - family: Indie Flower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf